### ISSUE TITLE
using space when searching either crashes or exits xfdashboard

### ISSUE THREAD

**Issue by nonamedotc** [gmc-holle/xfdashboard#61] opened 2015-01-05 01:27 UTC
It looks like using space when searching crashes xfdashboard (https://bugzilla.redhat.com/show_bug.cgi?id=1178578) or in my case it does not seem to crash but just vanishes without any messages.

Steps to reproduce - 

As an example, if you have orage installed, there are three choices typically
orage globaltime
orage preferences
orage calendar

type 'orage', hit space and try typing further. In my case, xfdashboard vanishes. Any diagnostics I can run?

**Comment by gmc-holle** [comment] 2015-01-05 07:40
Yes, I can confirm this issue and it should be fixed now. I'm really confused why it worked flawlessly with a single search term because I corrupted the string list when converting to lower case :/

Nevertheless it should work now. Can you confirm?

**Comment by nonamedotc** [comment] 2015-01-06 01:27
Perfect!!! This issue is fixed. Thanks for the quick fix. Tested on the master branch.

**Closed** 2015-01-06 01:27 UTC
Labels: bug
