### ISSUE TITLE
(Bug?) Drag to workspace 

### ISSUE THREAD

**Issue by theoar** [gmc-holle/xfdashboard#95] opened 2015-05-05 08:06 UTC
[Branch master]
I have problem with dragging windows to another workspaces. When I'm trying to drag something to other workspace I can't because the icon can be dragged only to the half of the screen.

![xfce](https://cloud.githubusercontent.com/assets/6282165/7468891/eaf1d368-f30d-11e4-894d-ae55d3cb73dd.png)

I marked dragged icon with red colour.
The yellow line shows border with I cannot cross while dragging icon to the right side.

[Branch 0.4]
Problem doesn’t accrue.

**Comment by gmc-holle** [comment] 2015-05-05 08:15
I have noticed this bug once before version 0.4 was released in a multi-monitor setup. But this code hasn't changed since then. So I'm confused why the branch "0.4" doesn't have this issue but the branch "master".

Do you have a multi-monitor setup? Do you compile with Xinerama enabled?

**Comment by theoar** [comment] 2015-05-05 09:09
No, I don't have multi-monitor, but I compile with enable Xinerma.

**Comment by gmc-holle** [comment] 2015-05-07 04:45
Oh, that makes it different ;) At the moment I guess that Clutter's stage window doesn't recognize the size after resizing the window to fullscreen. Could you please tell me what version of Clutter and GTK+/GDK you have installed? You use the system-wide installed libraries of Clutter and GTK+, aren't you?

**Comment by user501254** [comment] 2015-05-25 05:26
![screenshot_2015-05-25_10-51-18](https://cloud.githubusercontent.com/assets/6129517/7792193/0192507a-02cc-11e5-90ce-6a8c74ecab46.png)

I am having the same problem, I guess it was working fine on 15.04 but when I downgraded to 14.04(with XFCE 4.12) this showed up; on Xfdashboard 0.4.0.

**Comment by gmc-holle** [comment] 2015-05-25 17:34
If you two have the same issue then it's a bug :(

I'll try to reproduce the problem with an older version of Clutter as I use currently Clutter 1.20

**Comment by user501254** [comment] 2015-05-25 17:39
no problem, let me know if you need more information.

**Comment by gmc-holle** [comment] 2015-05-26 04:53
Sure, I have still one question ;) You are also using a single-monitor setup, aren't you? And what is your screen resolution?

**Comment by user501254** [comment] 2015-05-26 04:57
Yes, it's an ancient machine. 

Single monitor with a resolution of 1024x768.
I have 2 work-spaces enabled.

**Comment by gmc-holle** [comment] 2015-05-26 05:04
I know it's hard to tell but can you drag a window over more than the half of screen? I believe stop dragging does not happen exactly in the middle of screen but a little bit more to right edge of screen. Am I right?

**Comment by user501254** [comment] 2015-05-26 05:08
Yes, correct. Please see the image I included in an earlier comment. That's the farthest it goes (at least for me).

**Comment by gmc-holle** [comment] 2015-05-26 11:45
Sorry, I missed the dragged window icon in your screenshot and regarding to your screen resolution I guess I have to reintroduce the old hack I used before multi-monitor support was added. I believe that Clutter does not recognize that the window size changed when I went to fullscreen so it still thinks it has the initial size of 640x480 pixels. I think 640 pixels width matches your screenshot.

I'll send an update in this bug report as soon as I have reimplemented the old hack.

**Comment by user501254** [comment] 2015-05-26 13:00
Alright, I can help you test it. Best of luck! :smile:

**Comment by gmc-holle** [comment] 2015-05-26 16:39
Ok, my first try to solve this problem. I reimplemented the old hack to resize stage to screen size initially but now it also listen to screen size changes. This was done in commit b35ebd000bc6aa140dedc608cfa5b6cde19c9fe6

If possible and familiar with git, could you checkout the latest git and give it a try?

**Comment by user501254** [comment] 2015-05-27 10:13
I am quite familiar with git but I have no *(absolute 0)* experience in compiling Linux packages; I was actually expecting a precompiled deb file or something simpler. :sweat_smile: 

However I downloaded your repository.
- On 14.04 I couldn't install `libclutter-gtk-1.0-dev` and hence couldn't build the deb.
- On 15.04 everything worked just fine. 

**But since the bug was only in 14.04, I can't really say if the fix worked.** I can try again in a week or two.

**Comment by gmc-holle** [comment] 2015-05-28 06:18
I develop on systems running Gentoo Linux where nearly every package is built from the sources. So I have no experience in building binary packages and I can say: I'm not a packager.

I will include this fix (in hope it works) in version 0.4.1 - the next stable release.

I'll keep this bug open. As soon as I released a new stable version and a package is available for your system having this issue, please try again. If it is gone then (and I really hope so) we can close this bug.

**Comment by user501254** [comment] 2015-05-28 14:00
Sure, I will do that. Let's hope it works.

**Comment by user501254** [comment] 2015-05-30 08:30
Received the new update. Sadly the bug remains, no change.

**Comment by gmc-holle** [comment] 2015-05-30 18:08
Yes, because I'm stupid. I was checking the wrong Clutter version so this patch was never applied. I just release version 0.4.2 which should now work because in the meantime I was able to reproduce your problem and it went away :)

**Comment by user501254** [comment] 2015-05-31 06:43
received the latest update 0.4.2, works like a charm. We can close this now. Good job :smile:

**Comment by gmc-holle** [comment] 2015-05-31 06:44
Thanks for your feedback and I'm happy that it works now. :)

Closing bug.

**Closed by gmc-holle** 2015-05-31 06:44 UTC
Labels: bug

**Comment by jssilva25** [comment] 2015-09-12 22:57
I regret to say that I'm on 0.5.1, xubuntu 14.04.2, and I'm seeing this bug again. The dragged icon can only travel in what seems to be a 640x480 area starting on the top left corner.

I'm also seeing something else: when I hover the mouse over the half workspace pictures bar on the right, the bar doesn't slide out as it usually did, I don't know on which past version. Also, the mouse wheel works to switch the workspace but clicking works only on some workspace, couldn't make a corelation up to now, but it always comes back to the active workspace before calling xfdashboard, unless it was changed by the mouse wheel. Something similar happens with the windows in the screen center, some accept the click, some don't, but it always return to the window that was active before.

**Comment by gmc-holle** [comment] 2015-09-13 14:31
This bug becomes really annoying :( All issues you describe are known (to me) to happen when Clutter does not recognize the stage to resize and it still assumes it is a the default size of 640x480. Could you please tell me what version of Clutter and GTK+ you have installed?

``` 
dpkg -l | egrep -i "(clutter|gtk)"
```

Thanks

**Comment by gmc-holle** [comment] 2015-09-13 14:34
Ok, forget it. I was stupid because I only added the patch to the branch for stable version 0.4 but not to development version :(

Applied commit 3c0951bd304f5f912ab04bbdbc86385b39e71611 of branch 0.4 to master (development) branch.

**Comment by jssilva25** [comment] 2015-09-13 15:28
Thank you, very much, for such a quick reaction.

The repositories I'm using are xubuntu-dev/xfce-4.12/now (and trusty) and also extras/now and trusty, which still don't show any update. I guess I'll have to wait for it to reach those repositories to give you a feedback, unless you can advise better.

**Comment by jssilva25** [comment] 2015-09-14 23:59
To not keep us waiting, although I want to keep my LTS system as lean as possible, I built master and it works as expected, at a first glance. Thank you for your work.

**Comment by gmc-holle** [comment] 2015-09-15 04:02
Thanks for your feedback :)
