### ISSUE TITLE
Weird behaviour of terminals on "small workspaces"

### ISSUE THREAD

**Issue by alejandro-perez** [gmc-holle/xfdashboard#82] opened 2015-04-25 19:08 UTC
When I have a terminal opened, it is only displayed correctly on the small workspaces whenever they are on the current workspace. If I switch to another workspace, they are displayed "emtpy" (i.e. only the frame). See attached image for a better example.
![captura de pantalla_2015-04-25_21-01-14](https://cloud.githubusercontent.com/assets/2082536/7334276/3108b24e-eb8f-11e4-8975-efeea9ccc7a9.png)

**Comment by gmc-holle** [comment] 2015-04-25 19:10
Is this terminal window minimized?

**Comment by alejandro-perez** [comment] 2015-04-25 19:11
Nope. And I also have the workround for minimized widnows disabled, if that helps.

**Comment by gmc-holle** [comment] 2015-04-25 19:14
From the previous issues I assume you're running xfdashboard in daemon mode? While xfdashboard was running in daemon mode - was this terminal minimized at any time? What terminal do you use? Is it *Xfce4-terminal*?

**Comment by alejandro-perez** [comment] 2015-04-25 19:25
You're right, but sadly it happens in both modes. And it happens with xfce4-terminal and with mate-terminal.

**Comment by gmc-holle** [comment] 2015-04-25 19:31
Well, this is a sadly known problem which I try to solve even before the workaround for minimized windows was implemented (which only affects mininized windows at start-time of xfdashboard). Minimized windows are really hard to handle without the help of the window manager. I still try to find a general way independing of the window manager but it might be imposible and you know the result.

So please understand that I mark this issue as 'wont fix'. At least for now.

**Comment by alejandro-perez** [comment] 2015-04-25 19:59
I understand completely. Nevertheless, please note that the terminal was not minimized at start-time.

**Comment by alejandro-perez** [comment] 2015-04-28 10:29
More info: This is easily reproducible. No need to run in daemon mode.

1. Run xfdashboard in a desktop with a terminal open (it can be either xfce4-terminal, mate-terminal or even konsole). So, not particular to GTK
2. Go to overview (if running in daemon mode)
3. In overview, move to another desktop. The terminal in the side panel disappears (well, the frame remains, but the content becomes transparent).

None window is ever minimized.

**Comment by gmc-holle** [comment] 2015-04-29 17:35
This sounds like a duplicate to new issue #88 , isn't it?

**Comment by alejandro-perez** [comment] 2015-04-29 18:15
It is not related to location, but to how they are represented (emtpy). Besides, it happens in single monitor configurations.

On the contrary, #88 is multi-monitor specific, and not only for terminals.

**Comment by gmc-holle** [comment] 2015-05-01 15:33
I see it too. I don't know why the window texture to set to transparent before xfdashboard can handle the "Unmap" X11 event. Both terminal application rely on libvte. Maybe this library does something uncommon.

I don't believe I can fix this issue.

**Comment by alejandro-perez** [comment] 2015-05-01 15:55
:(. Well, it is somehow fixed when chosing to show icon instead of texture.

**Comment by gmc-holle** [comment] 2015-05-01 16:30
Yes, well, that should "fix" it because the window will be handled differently in this case

**Comment by gmc-holle** [comment] 2015-05-08 19:52
I don't know if it depends on the graphics card's driver but I cannot reproduce this problem at all time. At home I see this issue on an Intel GPU most the time but at work with a Nvidia GPU it works most the time. It seems to be a timing issue for the "Unmap" event and I don't think I can solve it.

**Comment by alejandro-perez** [comment] 2015-05-08 20:00
Curiously enough, I have an intel HD4000 at home, and an NVIDIA at work! But I see the issue everywhere, everytime. Sometimes the terminal dissapears, sometimes the texture gets confused. But definitely something goes wrong. I can live with the icon instead of the texture. Thanks!

**Comment by gmc-holle** [comment] 2015-05-08 20:11
The only way I think how this problem could be solved would be to get rid of CoglTexturePixmapX11 and implement my own version of it. But I didn't want to do it anytime (soon).

At the moment I'm sorry to keep this problem flagged as 'wontfix' :(

**Closed** 2015-05-08 20:11 UTC
Labels: wontfix
