### ISSUE TITLE
xfdashboard crashes when selected item in search view is destroyed

### ISSUE THREAD

**Issue by nonamedotc** [gmc-holle/xfdashboard#123] opened 2016-03-24 22:35 UTC
If "Gnome-Shell search provider" plugin is enabled, xfdashboard's search feature doesn't work and makes the application crash.

Version of the component:
xfdashboard-0.5.91-2.fc24.x86_64
xfdashboard-themes-0.5.91-2.fc24.x86_64

How reproducible:
Always

Steps to reproduce:
1) Open xfdashboard-settings.
2) Reach the "Plugins" spoke.
3) Enable the "Gnome-Shell search provider" plugin.
4) Close xfdashboard-settings.
5) Run xfdashboard.
6) Search for an application.

Actual results:
xfdashboard crashes and abrt catches the issue.

Downstream bug report with backtrace  - https://bugzilla.redhat.com/show_bug.cgi?id=1321186

**Comment by gmc-holle** [comment] 2016-03-25 07:57
I cannot reproduce the problem as all gnome-shell search providers I have installed at my system behave nicely and provide name and description. But I think I found the bug and fixed it with commit 564eecf58b8237bafcdf5dda98170e7efb560d19

Could you please test it?

**Comment by nonamedotc** [comment] 2016-03-26 12:10
Thank you! That seems to fix the crash. :+1: 

I will push an update to Fedora.

**Comment by nonamedotc** [comment] 2016-03-26 13:18
Looks like I spoke too soon. Crash still seems to persist unfortuately. I cannot reproduce this though. :(

backtrace - https://bugzilla.redhat.com/attachment.cgi?id=1140609

**Comment by gmc-holle** [comment] 2016-03-29 06:07
I see, I see :( You can reproduce the problem when the selected item in search view disappears, e.g. select an item from a Gnome-Shell search providerand change the search text to something that lets the selected item disappear because it does not match the search text anymore. Then xfdashboard crashed :(

**Comment by gmc-holle** [comment] 2016-03-29 12:03
I hope it is finally fixed now with commit a9df0f92dc3b711a39cd47bc4d1030c15eab29df and you will have a good feedback :)

**Comment by nonamedotc** [comment] 2016-03-31 02:38
Ok, this time I can definitely not reproduce the crash. I have tried several different search terms and clicked on random results .. played around quite a bit. No issues noticed.

So, I think this is fixed. :) Thanks!

**Comment by gmc-holle** [comment] 2016-03-31 18:01
Thanks for your positive feedback. That's very good news for me :)

So now as the last blocker is solved I can hopefully release the last release candicate.

Ready. Set. Go ... for 0.6.0 :D

**Closed by gmc-holle** 2016-03-31 18:01 UTC
Labels: BLOCKER
