### ISSUE TITLE
xfdashboard is unable to launch links

### ISSUE THREAD

**Issue by GreenLunar** [gmc-holle/xfdashboard#65] opened 2015-01-22 05:17 UTC
```
[Desktop Entry]
Version=1.0
Encoding=UTF-8
Type=Link
Name=Salix Online
Name[el]=Salix Online
Name[de]=Salix Online
Comment=Open the Salix homepage with Firefox
Comment[el]=Επισκευτείτε τον ιστότοπο του Salix
Comment[de]=Salix Homepage öffnen
Categories=Application;
URL=http://salix.sourceforge.net
Icon=salix-web
```

**Comment by gmc-holle** [comment] 2015-01-22 06:23
I need more information to clarify if it is a bug or an enhancement. So could you please tell me how you launch this desktop file? Is it a favourite stored in the quicklaunch (left side)? If it is where does this favourite come from? Did you drag'n'drop an item from the menu or from a search?

If you do not use a favourite to launch this link do start it from menu or from search view?

**Comment by GreenLunar** [comment] 2015-01-22 16:42
>So could you please tell me how you launch this desktop file?

I have this link located in ```~/.local/applications/```.

**Comment by gmc-holle** [comment] 2015-01-22 17:17
Sorry, I was meant to ask how you launch this item in xfdashboard - not where the desktop file is stored at?

Is it a favourite in the quicklaunch of xfdashboard on the left hand side? Do you use the search to find this link in xfdashboard or you do use the application menu (the one which shows categories first and then the applications in a category after you have clicked at one)?

**Comment by GreenLunar** [comment] 2015-01-23 05:41
> Do you use the search to find this link in xfdashboard or you do use the application menu

Yes, this Desktop Link Launcher should appear in Others category.

**Comment by gmc-holle** [comment] 2015-01-26 20:28
I have an idea. I do not know if it will work. But if this idea works, then this issue will be fixed. See issu e #67.

I'll keep this issue opens until the result of the issue is kown

**Comment by GreenLunar** [comment] 2015-01-26 22:03
Using Garcon would, likely, fix this issue.

**Comment by gmc-holle** [comment] 2015-02-09 19:26
Fixed with the latest commits which close issue #67 With these changes it is now possible to launch desktop files of type "Link" with the url provided in theses files. It is also possible to store these items as favourites in quicklaunch.

This should fix this issue.

**Comment by gmc-holle** [comment] 2015-02-09 19:27
Closing issue. If it does not work for you, please feel free to reopen this issue.

**Closed by gmc-holle** 2015-02-09 19:27 UTC
Labels: need (more) info
