### ISSUE TITLE
windows appear as vertically flattened strips again

### ISSUE THREAD

**Issue by nonamedotc** [gmc-holle/xfdashboard#149] opened 2017-05-22 18:36 UTC
When using xfdashboard 0.7.2, I am seeing the vertically flattened strips issue again. This is on Fedora 26 (pre-release).

```
# rpm -qa xfdashboard
xfdashboard-0.7.2-2.fc26.x86_64
```

The entire build log can be seen here - https://copr-be.cloud.fedoraproject.org/results/nonamedotc/xfce-414/fedora-26-x86_64/00552202-xfdashboard/build.log.gz

From the build log, here is the build configuration - 
```
Build configuration:
  Package:          xfdashboard
  Version:          0.7.2
  Revision:         
  Library version:  700:2:700
Compiler options:
  Compiler flags:   -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic 
  Debug level:      minimum
  Debug flags:      -DG_DISABLE_CAST_CHECKS
Library versions used:
  libwnck:          3.20.1
  clutter:          1.26.0
  cogl:             1.26.0
  gtk+:             3.22.12
  glib:             2.52.1
  gio:              2.52.1
  gio-unix:         2.52.1
  garcon:           0.6.0
  libxconf:         4.12.1
  libxfce4ui:       4.13.1
  libxfce4util:     4.12.1
  dbus-glib:        0.108
Tools used:
  glib-genmarshal:  glib-genmarshal
  glib-mkenums:     glib-mkenums
Features enabled:
  XComposite:       yes
  XDamage:          yes
  Xinerama:         yes
```
This is very similar to #141 .

![xfdashboard_flat_strips](https://cloud.githubusercontent.com/assets/1994161/26323148/bb5ddbe2-3efb-11e7-96bb-a7fc65ef670e.png)

**Comment by gmc-holle** [comment] 2017-06-02 07:16
Is it reproducible? Does it happen each time you use xfdashboard 0.7.2? Could you checkout latest git including commit 05b4a05268a50e2c8b63d459823f71e578f02d43 and check if this problem still exists?

**Comment by gsantner** [comment] 2017-06-07 16:25
Happens to me too, I'm on git HEAD. (Just note the workspace preview on the right too ). In total there were 5 windows.

![bildschirmfoto_2017-06-07_18-22-58](https://user-images.githubusercontent.com/6735650/26889444-82d936d0-4bae-11e7-9a4f-bda9def75fb1.png)

**Comment by gmc-holle** [comment] 2017-06-07 16:49
Can you safely reproduce this issue? If you can could you run xfdashboard in a terminal with the following command and paste the output here? Please review the output as it may contain privacy data.

```
XFDASHBOARD_DEBUG=windows /path/to/xfdashboard
```

Note: This command does not work if xfdashboard runs as daemon in background. In this case use this command:

```
XFDASHBOARD_DEBUG=windows XFDASHBOARD_FORCE_NEW_INSTANCE=1 /path/to/xfdashboard
```

**Comment by gsantner** [comment] 2017-06-07 16:54
Got it happening now again, but it never appears when xfdashboard is started. Only after some new windows get started.

The problem with your suggested command is, that both exit as soon as the dashboard closes once, and I need to do that to open something..

I tried both commands, with and without daemon mode. Killed xfdashboard before.

**Comment by gmc-holle** [comment] 2017-06-07 16:56
then kill all xfdashboard instances and run ```XFDASHBOARD_DEBUG=windows /path/to/xfdashboard --daemon``` in one terminal. Then use xfdashboard as usual. To quit xfdashboard run ``` xfdasbarrd -q```

**Comment by gsantner** [comment] 2017-06-07 16:58
Thats what I already did, as said above

**Comment by nonamedotc** [comment] 2017-06-14 01:20
Sorry for the late replies. I was away. I see the same behavior as described by @gsantner .

I can also attach logs if needed.

**Comment by gmc-holle** [comment] 2017-06-14 15:21
Hi,

getting logs would be great. I think the problem lies either in the live window actors or in the layout engine used in windows view.

If you can reproduce the problem properly with the latest git code, could you run the following command in a terminal and redirect the output into a file?

```
XFDASHBOARD_DEBUG=windows /path/to/xfdashboard
```

Just one question (also to @gsantner): Is the windows in the workspace selector at the right side (when using the default theme) always correct in position and size? Or are they also distorted?

**Comment by gsantner** [comment] 2017-06-14 17:03
I didnt recognize a issue at the workspace selection yet. I don't use it that much, but I would say in general it works

**Comment by nonamedotc** [comment] 2017-09-08 00:51
Apologies for the late response here.

I still see this issue with 0.7.3 on Fedora 26. I see no output when I run the debug command listed above. So, I am not really sure how to get any useful info.

**Comment by gmc-holle** [comment] 2017-09-15 08:43
@nonamedotc: Same question to you. Are only the windows in the windows view in the middle distored or also the windows in the workspace selector on the right side?

If all windows are distored then a general issue exists but (as far) it sounds that the layout manager in windows view does not work correctly.

**Comment by nonamedotc** [comment] 2017-09-15 11:17
It's only in the windows view and NOT the workspace selector. I forgot to get a screenshot last time it happened. I will try to get if and when it happens again (the flattening occurs randomly now)

**Comment by gsantner** [comment] 2017-10-13 22:44
I tried xfdasboard again today and just can say this still happens

**Comment by gmc-holle** [comment] 2017-10-16 05:38
Is it reproducible or does it happen out of the blue, i.e sometimes it work and then again it does not work? If it is (mostly) reproducible then it would make sense to add some debug messages. I also have an idea to make the requests to retrieve the windows' widths and heights more robust.

**Comment by gsantner** [comment] 2017-10-16 08:04
if it happens once, i can toggle dashboard and it still happens. it usually goes away after starting or closing something

**Comment by gmc-holle** [comment] 2017-10-16 15:32
I checked the calculation of the layout manager used in windows view but it should work and I never had this issue on any system I have access at. So I re-read the logs you provided and again I did not find any hint. Last but not least I looked at your screenshot again to look at the size of each window, their aspect ratio etc. to find any hint ... but nothing.

Ok, not "nothing". This time I look at the content of each window and I found the terminal running xfdashboard. There are a lot of assertion failure message "XFDASHBOARD_IS_WINDOW_TRACKER_WINDOW(self)" when the function xfdashboard_window_tracker_window_get_geometry() is called. In case of assertion the window size is not determined and the value "returned" is uninitialized and is undeterminable.

Are these message still printed to console if you hit this problem? Then the question is why this assertion fails. At the moment I would say - only a backtrace in gdb could tell :(

**Comment by gmc-holle** [comment] 2017-10-16 15:39
Could you apply this patch to latest git? It will initialize the value at least to zero and will force a fallback to the old method to determine window size. It will not solve the assertion failure if they are still printed and I'm also interested in this information.

```
diff --git a/libxfdashboard/live-window-simple.c b/libxfdashboard/live-window-simple.c
index ea85363..5958430 100644
--- a/libxfdashboard/live-window-simple.c
+++ b/libxfdashboard/live-window-simple.c
@@ -278,8 +278,9 @@ static void _xfdashboard_live_window_simple_get_preferred_height(ClutterActor *s
        {
                gint                                                    windowHeight;
 
+               windowHeight=0;
                xfdashboard_window_tracker_window_get_geometry(priv->window, NULL, NULL, NULL, &windowHeight);
-               if(windowHeight<=0.0)
+               if(windowHeight<=0)
                {
                        ClutterContent                          *content;
                        gfloat                                          childNaturalHeight;
@@ -324,8 +325,9 @@ static void _xfdashboard_live_window_simple_get_preferred_width(ClutterActor *se
        {
                gint                                                    windowWidth;
 
+               windowWidth=0;
                xfdashboard_window_tracker_window_get_geometry(priv->window, NULL, NULL, &windowWidth, NULL);
-               if(windowWidth<=0.0)
+               if(windowWidth<=0)
                {
                        ClutterContent                          *content;
                        gfloat                                          childNaturalWidth;
```

**Comment by gsantner** [comment] 2017-10-16 15:52
you can also add some prints in the patch if you want to know some value

**Comment by gmc-holle** [comment] 2017-10-16 16:18
Yes, I can spam your console ;)

```
diff --git a/libxfdashboard/live-window-simple.c b/libxfdashboard/live-window-simple.c
index ea85363..fd0350e 100644
--- a/libxfdashboard/live-window-simple.c
+++ b/libxfdashboard/live-window-simple.c
@@ -278,8 +278,10 @@ static void _xfdashboard_live_window_simple_get_preferred_height(ClutterActor *s
 	{
 		gint							windowHeight;
 
+		windowHeight=0;
 		xfdashboard_window_tracker_window_get_geometry(priv->window, NULL, NULL, NULL, &windowHeight);
-		if(windowHeight<=0.0)
+		XFDASHBOARD_DEBUG(self, WINDOWS, "[issue 149] called xfdashboard_window_tracker_window_get_geometry from %s -> [%dx%d]", __func__, 0, windowHeight);
+		if(windowHeight<=0)
 		{
 			ClutterContent				*content;
 			gfloat						childNaturalHeight;
@@ -324,8 +326,10 @@ static void _xfdashboard_live_window_simple_get_preferred_width(ClutterActor *se
 	{
 		gint							windowWidth;
 
+		windowWidth=0;
 		xfdashboard_window_tracker_window_get_geometry(priv->window, NULL, NULL, &windowWidth, NULL);
-		if(windowWidth<=0.0)
+		XFDASHBOARD_DEBUG(self, WINDOWS, "[issue 149] called xfdashboard_window_tracker_window_get_geometry from %s -> [%dx%d]", __func__, windowWidth, 0);
+		if(windowWidth<=0)
 		{
 			ClutterContent				*content;
 			gfloat						childNaturalWidth;
diff --git a/libxfdashboard/live-window.c b/libxfdashboard/live-window.c
index 6af3af4..8e74b23 100644
--- a/libxfdashboard/live-window.c
+++ b/libxfdashboard/live-window.c
@@ -43,6 +43,7 @@
 #include <libxfdashboard/stylable.h>
 #include <libxfdashboard/application.h>
 #include <libxfdashboard/compat.h>
+#include <libxfdashboard/debug.h>
 
 
 /* Define this class in GObject system */
@@ -765,7 +766,9 @@ static void _xfdashboard_live_window_allocate(ClutterActor *self,
 		{
 			gint						windowWidth, windowHeight;
 
+			windowWidth=windowHeight=0;
 			xfdashboard_window_tracker_window_get_geometry(window, NULL, NULL, &windowWidth, &windowHeight);
+			XFDASHBOARD_DEBUG(self, WINDOWS, "[issue 149] called xfdashboard_window_tracker_window_get_geometry from %s -> [%dx%d]", __func__, windowWidth, windowHeight);
 			if(windowWidth>largestWidth) largestWidth=windowWidth;
 			if(windowHeight>largestHeight) largestHeight=windowHeight;
 		}
diff --git a/libxfdashboard/live-workspace.c b/libxfdashboard/live-workspace.c
index 646361b..a255d97 100644
--- a/libxfdashboard/live-workspace.c
+++ b/libxfdashboard/live-workspace.c
@@ -783,7 +783,9 @@ static void _xfdashboard_live_workspace_allocate(ClutterActor *self,
 		if(!window || !XFDASHBOARD_IS_WINDOW_TRACKER_WINDOW(window)) continue;
 
 		/* Get real size of child */
+		x=y=w=h=0;
 		xfdashboard_window_tracker_window_get_geometry(window, &x, &y, &w, &h);
+		XFDASHBOARD_DEBUG(self, WINDOWS, "[issue 149] called xfdashboard_window_tracker_window_get_geometry from %s -> [%dx%d]", __func__, w, h);
 
 		/* Calculate translated position and size of child */
 		childAllocation.x1=x-visibleArea.x1;
```

Please apply this patch instead of the one above and re-run with xfdashboard with debug enabled:

```
XFDASHBOARD_DEBUG=windows xfdashboard
```

**Comment by gsantner** [comment] 2017-10-16 16:46
any grep filter i should apply in advance?

**Comment by gmc-holle** [comment] 2017-10-16 16:58
Not really. Maybe `... | grep -B 3 "[issue 149]"`? I hope the corresponding assertion message is fetched by `grep` and within the thres lines before these additional debug messages.

**Comment by gsantner** [comment] 2017-10-16 17:05
ok, then im just redirecting output and you can filter what you need then

**Comment by gsantner** [comment] 2017-10-21 12:50
I cannot give you debug log, because xfdashboard always insta-quits... doesnt depend if i'm doing in daemon mode or not, it gives one time an output, but as soon as I go out once of window view debug shell exists

**Comment by gsantner** [comment] 2017-10-23 11:15
I think I get it why it still happens, but not in debug runs. I got xfdashboard daemon in autostart, but installation runs to /usr/local/bin/, therefore /usr/bin/ gets executed and I get the latest release running. Is there any command to get more version information? like --git-commit? --version does show nothing

**Comment by gmc-holle** [comment] 2017-10-24 15:04
No, I don't know any way to get the version number of the running after it is running. The version is only shown in the main instance at start-up - including git-commit if it is not a official release. After that point it isn't shown anymore.

So yes, adding a command-line option `--version` would make sense. It should show the version of the application executed and the version of the daemon instance, if there is running any daemon instance. I hope I can implement that.

**Comment by gmc-holle** [comment] 2017-10-24 16:32
`--version` was implemented in latest commit but in a very simple way as the terminal will only show the version of currently executed (new instance) of xfdashboard. If a daemon is running in background then it will also print its version with another prefix but in the terminal where the daemon is running. If the daemon was not started in a seperated terminal then the output is usually redirected to `~/.xsession-errors` by X11 session.

**Comment by gsantner** [comment] 2017-10-24 17:27
I think its perfectly fine to just exectute version output and then exit when running --version

**Comment by gsantner** [comment] 2018-01-11 22:55
Sorry for the noise, only wanted to tell that sadly this is still happening (I am on current HEAD https://github.com/gmc-holle/xfdashboard/commit/2461f52972d301b6b20a9272d056518265d13ae3), still thanks for your countless times trying to fix it once for all 👍

**Comment by gmc-holle** [comment] 2018-05-07 04:38
Sorry, I still haven't seen the problems reported here neither on my main system nor at work. So I still have no clue what could cause it and the problem exists as the screenshots show.

So just a shot into the dark: Do you all use a NVIDIA GPU as primary device? That means that your X server is mainly running at such a graphics card. Do you use the proprietary driver from NVIDIA or nouveau? My machines also have such a device but the laptop is a Optimus mainly running on Intel GPU and only the GPU-intensive apps like games run on NVIDIA and the other machine has only the NVIDIA one as primary card but does not run any GPU-intensive apps as the machine+GPU is too slow ;)

**Comment by nonamedotc** [comment] 2018-06-16 17:53
Ok, I wanted to test this extensively before responding. Here are my observations. I see this (flattened strips or small boxes) in three systems with the following configurations - 

(1) i7-4810 MQ, NVIDIA GeForce GTX 860M
(2) i7-4900 MQ, NVIDIA Quadro K1100M
(3) i7-4600U, integrated graphics

Both the nvidia laptops are running nouveau drivers. None of these laptops run anything that can be called too graphics intensive. Laptop (1) is always connected to an external monitor through a VGA port. Other than that, there is nothing "special" about any of these systems.

The occurrence of flattened strips are completely random and there is very little I can do to reproduce them - as far as I can tell.

**Comment by gsantner** [comment] 2018-06-17 10:09
I see the stripes happen very often right now. It doesn't happen at any time when xfdashboard gets run freshly. What I'm doing is restarting the xfdashboard background daemon every 5 minutes:

`cron line`:
```
*/5 * * * * DISPLAY=:0 bash "/folder/desktopctl.sh" "xfdashboard-restart" > /dev/null 2>&1
```
`desktopctl.sh`:
```
#!/bin/bash
xfdashboard_restart(){
        pid=`ps -ax | grep "/usr/bin/xfdashboard" | grep -v grep | xargs | cut -d' ' -f1`
        [ -z "$pid" ] && return
        # Wait till xfdashboard gets invisible (dont kill e.g. search)
        delayme=1
        while [ $delayme -eq 1 ] ; do
                for wid in $(xdotool search --pid "$pid") ; do
                        active=`xdotool getactivewindow`
                        [ "$active" == "$wid" ] && sleep 10 && continue
                done
                delayme=0
        done

        # Restart. xfdashboard daemon sometimes restarts itself quickly
        for i in $(seq 1 30) ; do killall xfdashboard 2>&1 > /dev/null ; done
        /usr/bin/xfdashboard -d > /dev/null 2>&1 &
        disown
}
[ "$1" == "xfdashboard-restart" ] && xfdashboard_restart > /dev/null 2>&1
```

**Comment by gsantner** [comment] 2018-06-17 12:30
I see the stripes happen very often right now. It doesn't happen at any time when xfdashboard gets run freshly. What I'm doing is restarting the xfdashboard background daemon every 30 minutes:

```
#!/bin/bash

# Cron: */30 * * * * DISPLAY=:0 bash "/folder/desktopctl.sh" "xfdashboard-restart" > /dev/null 2>&1
xfdashboard_restart(){
        # Wait till xfdashboard gets invisible (dont kill e.g. search)
        pid=`ps -ax | grep "/usr/bin/xfdashboard" | grep -v grep | xargs | cut -d' ' -f1`
        while [ -n "$pid" ] ; do
                for wid in $(xdotool search --pid "$pid") ; do
                        [ "$(xdotool getactivewindow)" == "$wid" ] && sleep 10 && continue
                done
                break
        done

        # Restart. xfdashboard daemon sometimes restarts itself quickly
        for i in $(seq 1 30) ; do killall xfdashboard > /dev/null 2>&1 ; done
        /usr/bin/xfdashboard -d > /dev/null 2>&1 &
        disown
}
[ "$1" == "xfdashboard-restart" ] && xfdashboard_restart > /dev/null 2>&1
```

This might be a big workaround which doesn't really solve the problem, but it works. Maybe up/down the 30 to needs.

**Comment by gsantner** [comment] 2018-06-19 14:35
has no such stripes anymore since done the above

**Comment by gmc-holle** [comment] 2018-06-19 16:15
Ok, let me summarze. This problem only happens when running in daemon mode for some time. Have you noticed that only old or new windows between suspend and resume are affected. Or are always *all* windows affected? I have an idea what may cause the problem but it would only affected the windows before xfdashboard was put to background. All new windows created were not affected by this problem if my idea is right. Any chance you can try to confirm this assumption?

**Comment by gsantner** [comment] 2018-06-19 17:17
Yes. daemon only.
Usually most, but sometimes except 1-2 windows. E.g. can see Firefox webpage sometimes while others stripe.

**Comment by nonamedotc** [comment] 2018-06-20 01:46
> ave you noticed that only old or new windows between suspend and resume are affected. Or are always all windows affected?

For me, it's random. Sometimes all windows are messed up. Sometimes only a small subset are messy.

Also, one action that gets the windows to show up normal is to switch workspace from within xfdashboard using the mouse wheel. Everything is fine until it happens again.

**Comment by gsantner** [comment] 2018-06-22 19:28
Everytime I have noticed this bug I have added the cronjob as above. Have it now on 3 devices and since that zero problems.
So definetly a problem in daemon mode.

**Comment by gmc-holle** [comment] 2018-06-25 04:37
Yes, I have not seen this bug directly when testing daemon mode the last week but I saw a lot of warnings and critical messages about invalid instances. I believe I could narrow it down to the new code for implementation of different backends like X11 and GDK. It must miss some events since this time especially those about closed windows as the warning and criticals expect invalid pointers to window instances which seem to be freed (not existing). I think this bug can be provoked when a child window of an application was created and closed, e.g. a open/save dialog of an application or a printing dialog. I need further checks but maybe you can see these coincidences also?

**Comment by gmc-holle** [comment] 2018-06-26 17:15
I think I got it. The live window actors for sub-windows of a top-level window, e.g. open/save dialogs,  were not destroyed when the window was closed. This left an invalid instances which caused a height and width of zero because the sanity check were not fulfilled resulting in strange calculation of the top-level window size. Also the content of window closed (and not valid anymore) was not freed so it used an invalid texture or better said, we don't know what is stored in the texture used for the (now) non-existing window. It will be an distorted image as we know now ;)

The last commit 0a1fe71d54d443a272af410bfca3748d9b089e33 should fix this issue and I hope the cron job is now not needed anymore. Can you test it?

**Comment by gsantner** [comment] 2018-06-26 17:56
will give it a shot on desktop when I get to it

**Comment by gsantner** [comment] 2018-07-01 19:32
Hey, have this some days now.
It crashes sometimes with segmentation fault.
Too, sometimes daemon has a crash-restart loop, where I shortly see Dashboard, it quits, and again Dashboard. That roughly 10 times in a delay of like 500ms.
I have seen less striped windows, but I remember to have seen them at least one time (where I explicitly took a look).

**Comment by gmc-holle** [comment] 2018-07-17 16:14
I'm running xfdashboard in daemon mode for some days now and I haven't seen any distorted windows nor I have seen and critical or warning message on console. No segfaults at all.

Can anyone confirm that the last commits fixed the problem? I really hope and have my fingers crossed.

**Comment by gmc-holle** [comment] 2018-08-08 11:00
I found some minor non-fatal warnings and fixed them. I consider to mark this issue as fixed ... finally :)

**Closed by gmc-holle** 2018-08-08 11:00 UTC
Labels: bug, need (more) info

**Comment by gsantner** [comment] 2018-08-08 19:20
Did write a comment back then, but somehow octodroid didnt post 

trying current master
