### ISSUE TITLE
DUAL MONITOR - Dragging a window miniature to a different monitor should put the window on that monitor

### ISSUE THREAD

**Issue by alejandro-perez** [gmc-holle/xfdashboard#98] opened 2015-09-09 07:29 UTC
In the overview mode, when I draft a window miniature (e.g. chromium) to a different monitor (e.g. right one), nothing happens. If I move it to a different monitor on a different workspace, it just moves to that workspace, but remains on the same monitor.

**Comment by gmc-holle** [comment] 2015-09-09 09:38
Yes, I know. I already thought about this issue.

The problem is how to tell the window manager to move the window to a different position. I also have to choose to keep the window maximized and/or to resize it. That's not as easy as it may sound. :(

**Comment by gmc-holle** [comment] 2015-12-22 11:24
Implemented with commit ac42dd789cd41d94377db6dc37f2e2406da52157 but lacks 100% proper window positioning and moving maximized windows. I have to see if I get this issue also solved.

**Comment by gmc-holle** [comment] 2015-12-22 11:25
I forgot to say that only windows displayed in windows view (not in the workspace selector) can be moved between monitors.

**Comment by gmc-holle** [comment] 2015-12-22 12:03
Window position should now be correct with commit ae7e60a33ef7aad46e012072328c73db771669ac . But I could only test it on two connected monitors having the same resolution.

**Comment by alejandro-perez** [comment] 2015-12-23 07:19
Thanks! I will try to test it with different resolutions (i.e. LVDS and TV)

**Comment by gmc-holle** [comment] 2017-05-04 06:48
I use this feature now for over a year by myself and it works here. As no one claimed an issue about this feature I assume it is "fixed" and I'm closing this issue.

**Closed by gmc-holle** 2017-05-04 06:48 UTC
Labels: enhancement
