### ISSUE TITLE
g_cclosure_marshal_VOID__VOID: assertion 'n_param_values == 1' failed

### ISSUE THREAD

**Issue by gsantner** [gmc-holle/xfdashboard#165] opened 2018-02-02 22:12 UTC
Hi there,
tried xfdashboard today and found this in the logs. It seems not to crash anything (that I would notice), but produces many `GLib-GObject-CRITICAL **: g_cclosure_marshal_VOID__VOID: assertion 'n_param_values == 1' failed` messages. Tell me if info missing.

Version: xfdashboard-0.7.5git.2461f52
First try on Cinnamon DE, Arch Linux

[xfdashboard-debug.log](https://github.com/gmc-holle/xfdashboard/files/1691003/xfdashboard-debug.log)

EDIT:  
Sometime too these errors appear, now too - 
where in fact the mouse is in the edge and xfdashboard does not appear:
```
(xfdashboard:27022): xfdashboard-WARNING **: Cannot switch to unknown view 'windows'

(xfdashboard:27022): xfdashboard-WARNING **: Cannot switch to unknown view 'windows'

(xfdashboard:27022): xfdashboard-WARNING **: Cannot switch to unknown view 'windows'

(xfdashboard:27022): xfdashboard-WARNING **: Cannot switch to unknown view 'windows'

(xfdashboard:27022): xfdashboard-WARNING **: Cannot switch to unknown view 'windows'

(xfdashboard:27022): xfdashboard-WARNING **: Cannot switch to unknown view 'windows'
```

**Comment by gsantner** [comment] 2018-02-02 22:15
Sometime too these appear, now too:

`
(xfdashboard:27022): xfdashboard-WARNING **: Cannot switch to unknown view 'windows'

(xfdashboard:27022): xfdashboard-WARNING **: Cannot switch to unknown view 'windows'

(xfdashboard:27022): xfdashboard-WARNING **: Cannot switch to unknown view 'windows'

(xfdashboard:27022): xfdashboard-WARNING **: Cannot switch to unknown view 'windows'

(xfdashboard:27022): xfdashboard-WARNING **: Cannot switch to unknown view 'windows'

(xfdashboard:27022): xfdashboard-WARNING **: Cannot switch to unknown view 'windows'
`

where in fact the mouse is in the edge and xfdashboard does not appear

**Comment by gsantner** [comment] 2018-02-03 21:02
Heres another log (this times from MATE DE. After opening xfdashboard like 5 times, it won't show up anymore. Below I went to the top edge and went out again, nothing appeard (but did 4 times before)


Going to top-right edge
```
xfdashboard-Message: [        +54,7584]:[XfdashboardWindowTrackerX11@0x564668f8f700]:[WINDOWS]:x11/window-tracker-x11.c:425: Window 'Obere Leiste' changed position and/or size
xfdashboard-Message: [        +54,7625]:[XfdashboardWindowTrackerX11@0x564668f8f700]:[WINDOWS]:x11/window-tracker-x11.c:705: Window stacking has changed
xfdashboard-Message: [        +54,7625]:[XfdashboardThemeCSS@0x564669734cd0]:[STYLE]:theme-css.c:2785: Looking up matches for XfdashboardLiveWindowSimple.window-state-pinned 
xfdashboard-Message: [        +54,7625]:[XfdashboardThemeCSS@0x564669734cd0]:[STYLE]:theme-css.c:2843: Found 0 properties for XfdashboardLiveWindowSimple.window-state-pinned in 0,000174 seconds
xfdashboard-Message: [        +54,7625]:[XfdashboardThemeCSS@0x564669734cd0]:[STYLE]:theme-css.c:2785: Looking up matches for XfdashboardLiveWindowSimple.window-state-maximized 
xfdashboard-Message: [        +54,7625]:[XfdashboardThemeCSS@0x564669734cd0]:[STYLE]:theme-css.c:2843: Found 0 properties for XfdashboardLiveWindowSimple.window-state-maximized in 0,000124 seconds
xfdashboard-Message: [        +54,9130]:[XfdashboardWindowTrackerBackendX11@0x564669178970]:[WINDOWS]:x11/window-tracker-backend-x11.c:645: Disconnecting handler 2702 for signal 'state-changed' at window 0x564669dd9210 (wnck-window=0x5646690afa00)
xfdashboard-Message: [        +54,9130]:[XfdashboardWindowTrackerBackendX11@0x564669178970]:[WINDOWS]:x11/window-tracker-backend-x11.c:664: Disconnecting handler 2703 for signal 'active-window-changed' at screen 0x5646690b4790 of window 0x564669dd9210 (wnck-window=0x5646690afa00)
xfdashboard-Message: [        +54,9130]:[XfdashboardWindowTrackerBackendX11@0x564669178970]:[WINDOWS]:x11/window-tracker-backend-x11.c:682: Disconnecting handler 2704 for signal 'screen-size-changed' at window 0x564669dd9210 (wnck-window=0x5646690afa00)
xfdashboard-Message: [        +54,9130]:[XfdashboardWindowContentX11@0x56466925e3e0]:[WINDOWS]:x11/window-content-x11.c:975: Successfully suspended live texture updates for window 'gregor@terminal:~'
xfdashboard-Message: [        +54,9130]:[XfdashboardWindowContentX11@0x56466925e6e0]:[WINDOWS]:x11/window-content-x11.c:975: Successfully suspended live texture updates for window 'x-caja-desktop'
```
(nothing appears..). Leaving edge.

```
xfdashboard-Message: [        +57,3737]:[XfdashboardWindowTrackerX11@0x564668f8f700]:[WINDOWS]:x11/window-tracker-x11.c:705: Window stacking has changed
xfdashboard-Message: [        +57,3747]:[XfdashboardThemeCSS@0x564669734cd0]:[STYLE]:theme-css.c:2785: Looking up matches for XfdashboardLiveWindowSimple.window-state-pinned 
xfdashboard-Message: [        +57,3747]:[XfdashboardThemeCSS@0x564669734cd0]:[STYLE]:theme-css.c:2843: Found 0 properties for XfdashboardLiveWindowSimple.window-state-pinned in 0,000175 seconds
xfdashboard-Message: [        +57,3747]:[XfdashboardThemeCSS@0x564669734cd0]:[STYLE]:theme-css.c:2785: Looking up matches for XfdashboardLiveWindowSimple.window-state-maximized 
xfdashboard-Message: [        +57,3747]:[XfdashboardThemeCSS@0x564669734cd0]:[STYLE]:theme-css.c:2843: Found 0 properties for XfdashboardLiveWindowSimple.window-state-maximized in 0,000125 seconds
```

**Comment by gmc-holle** [comment] 2018-02-06 15:48
Ok, lot of different issue in one report ;) I go through them step-by-step.

1.) The main issue `g_cclosure_marshal_VOID__VOID: assertion 'n_param_values == 1' failed` was only visible if the plugin `middle-click-window-close` was enabled. Then a wrong signal signature was discovered for signal `actor-created` at `XfdashboardStage`. This was fixed with commit ab61859bb14c7eb7b71125546dfc1c447aba9f46

2.) The issue `Cannot switch to unknown view 'windows'` is known and caused by me when changing the view IDs (internal name). Your configuration still contains the old ID `windows` instead of `builtin.windows`. This should be fixed by changing the option "Switch to view on resume" to a different value and then back to the old value if is set to anything else than "Do nothing". Another source could be the command you execute to bring `xfdashboard` to front. Do you use the command-line parameter `--view`? Then check the value passed to this parameter.

3.) I do not use MATE desktop but it seems one of the more problematic ones. I will check if the `hot-corner` plugin works for me (on Xfce). If it works I think I cannot fix it. I have already another issue for the daemon mode not working under MATE and it is still unsolved :(

**Comment by gmc-holle** [comment] 2018-02-06 17:29
Hmm ... the `hot-corner` plugins is working for me at Xfce with workspace streched over two monitors. I use GTK+ Version 3.22.19. Which version do you use?

**Comment by gmc-holle** [comment] 2018-02-06 17:31
BTW the debug log looks to be shortened. Do you really don't get a warning about `hot-corner` has to be disabled because of sth.?

**Comment by gsantner** [comment] 2018-02-06 18:35
> Ok, lot of different issue in one report ;) I go through them step-by-step.
> 
> 1.) The main issue g_cclosure_marshal_VOID__VOID: assertion 'n_param_values == 1' failed was only visible if the plugin middle-click-window-close was enabled. Then a wrong signal signature was discovered for signal actor-created at XfdashboardStage. This was fixed with commit ab61859

\-


> 2.) The issue Cannot switch to unknown view 'windows' is known and caused by me when changing the view IDs (internal name). Your configuration still contains the old ID windows instead of builtin.windows. This should be fixed by changing the option "Switch to view on resume" to a different value and then back to the old value if is set to anything else than "Do nothing". Another source could be the command you execute to bring xfdashboard to front. Do you use the command-line parameter --view? Then check the value passed to this parameter.

These are my bindings (which I used too on Mate), should be fine. I also tried toggling via `-t` without `--view`.

```
.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-keyboard-shortcuts.xml
45:      <property name="&lt;Super&gt;s" type="string" value="xfdashboard --view builtin.windows -t"/>
46:      <property name="&lt;Super&gt;a" type="string" value="xfdashboard --view builtin.applications -t"/>
47:      <property name="&lt;Alt&gt;F1" type="string" value="xfdashboard --view builtin.windows -t"/>
```

> 3.) I do not use MATE desktop but it seems one of the more problematic ones. I will check if the hot-corner plugin works for me (on Xfce). If it works I think I cannot fix it. I have already another issue for the daemon mode not working under MATE and it is still unsolved :(

I too usually, but I gave it a try once a time.

> Hmm ... the hot-corner plugins is working for me at Xfce with workspace streched over two monitors. I use GTK+ Version 3.22.19. Which version do you use?

Single Monitor.  
```
local/gtk3 3.22.26+161+g60750b3ffd-1
    GObject-based multi-platform GUI toolkit
local/kde-gtk-config 5.11.5-1 (plasma)
    GTK2 and GTK3 Configurator for KDE
local/gtkmm 2.24.5-2
    C++ bindings for gtk2
local/gtkmm3 3.22.2+2+g3002ed86-1
    C++ bindings for GTK+ 3
```


> BTW the debug log looks to be shortened. Do you really don't get a warning about hot-corner has to be disabled because of sth.?

nothing disabled. debug mode ALL.



hope theres some  useable feedback :)

**Comment by gsantner** [comment] 2018-02-06 18:54
btw, yes I am sure there hotcorner plugin enabled, otherwise there would be no log coming up when going to the edge :D

**Comment by gmc-holle** [comment] 2018-03-26 14:32
Sorry for the late reply but I'm still busy with renovating after moving. :/

Ok, I think point 1.) can be marked as solved.

Regarding 2.) I tried your key bindings on console and they work as expected - in daemon mode and standalone (non-daemon) mode. Super-A should open xfdashboard and showing the applications menu. You have only one xfdashboard version installed? Regarding your log files I looks like that xfdashboard is installed system-wide, either at /usr/... or /usr/local/... There are no conflicting version installed, e.g. one system-wide installation running the daemon and a git version running at a different path or vice versa?

3.) I hope some day I will discover why some other window manager behave different to xfwm4. But at the moment I have no clue :(

**Comment by gsantner** [comment] 2018-03-26 15:01
I think the main issue is resolved, and therefore would close this. Regarding others - I just tried mate and reported the problems, I don't use it currently/have it not installed.

**Closed** 2018-03-26 15:02 UTC

**Comment by gsantner** [comment] 2018-05-02 16:16
@gmc-holle Are you available somewhere sometime for a chat? Would like to get some infos regarding xfdashboard and dev, but IRC/XMPP/Matrix discussion is easier for this.

**Comment by gmc-holle** [comment] 2018-05-02 17:33
No problem. I prefer XMPP so you add me via my email address for private chat. I have create a MUC room at `xfdashboard@froevel.de` for public chat but I don't know if really works ;)
